name: Mission Control

on:
  push:
    branches:
      - 'dev'
    paths:
      - 'MissionControl-v2/**'
      - 'source/com.unity.cluster-display/Runtime/MissionControl/Shared/IIncrementalCollectionObject.cs'
      - 'source/com.unity.cluster-display/Runtime/MissionControl/Shared/IncrementalCollection.cs'
      - 'source/com.unity.cluster-display/Runtime/MissionControl/Shared/IncrementalCollectionObjectData.cs'
      - 'source/com.unity.cluster-display/Runtime/MissionControl/Shared/IncrementalCollectionsName.cs'
      - 'source/com.unity.cluster-display/Runtime/MissionControl/Shared/IncrementalCollectionUpdate.cs'
      - 'source/com.unity.cluster-display/Runtime/MissionControl/Shared/IReadOnlyIncrementalCollection.cs'
      - 'source/com.unity.cluster-display/Runtime/MissionControl/Shared/ObservableObjectsName.cs'
      - 'TestProjects/MissionControlTests/Assets/Tests/AsyncConditionVariableTests.cs'
      - 'TestProjects/MissionControlTests/Assets/Tests/IncrementalCollectionTests.cs'
      - 'TestProjects/MissionControlTests/Assets/Tests/ObjectReferenceEqualityComparer.cs'

  pull_request:
    branches:
      - 'dev'
    paths:
      - 'MissionControl-v2/**'
      - 'source/com.unity.cluster-display/Runtime/MissionControl/Shared/IIncrementalCollectionObject.cs'
      - 'source/com.unity.cluster-display/Runtime/MissionControl/Shared/IncrementalCollection.cs'
      - 'source/com.unity.cluster-display/Runtime/MissionControl/Shared/IncrementalCollectionObjectData.cs'
      - 'source/com.unity.cluster-display/Runtime/MissionControl/Shared/IncrementalCollectionsName.cs'
      - 'source/com.unity.cluster-display/Runtime/MissionControl/Shared/IncrementalCollectionUpdate.cs'
      - 'source/com.unity.cluster-display/Runtime/MissionControl/Shared/IReadOnlyIncrementalCollection.cs'
      - 'source/com.unity.cluster-display/Runtime/MissionControl/Shared/ObservableObjectsName.cs'
      - 'TestProjects/MissionControlTests/Assets/Tests/AsyncConditionVariableTests.cs'
      - 'TestProjects/MissionControlTests/Assets/Tests/IncrementalCollectionTests.cs'
      - 'TestProjects/MissionControlTests/Assets/Tests/ObjectReferenceEqualityComparer.cs'

env:
  projectpath: 'MissionControl-v2/MissionControl.sln'

jobs:
  test:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ${{ env.projectpath }}
    - name: Build
      run: dotnet build --no-restore ${{ env.projectpath }}
    - name: Test
      run: dotnet test -m:1 --no-build --verbosity normal ${{ env.projectpath }}
