name: Mission Control

on:
  push:
    branches:
      - 'dev'
    paths:
      - 'MissionControl-v2/**'

  pull_request:
    branches:
      - 'dev'
    paths:
      - 'MissionControl-v2/**'

env:
  projectpath: 'MissionControl-v2/MissionControl.sln'

jobs:
  test:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ${{ env.projectpath }}
    - name: Build
      run: dotnet build --no-restore ${{ env.projectpath }}
    - name: Test
      run: dotnet test --no-build --verbosity normal ${{ env.projectpath }}
